apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-dotnet60-basic-uxma
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-dotnet60-basic-uxma
    app.kubernetes.io/part-of: dotnet-component
  name: devfile-sample-dotnet60-basic-uxma
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: devfile-dotnet-deploy
      app.kubernetes.io/instance: devfile-sample-dotnet60-basic-uxma
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: devfile-dotnet-deploy
        app.kubernetes.io/instance: devfile-sample-dotnet60-basic-uxma
    spec:
      containers:
      - image: quay.io/rsoaresd_org/spi-demos-fgmh-tenant/dotnet-component/devfile-sample-dotnet60-basic-uxma@sha256:ea18bb6014d79fb2ffb5227d1663370f598e9ffde53a8d0fe756c8b182902824
        imagePullPolicy: Always
        name: main
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
